CREATE TABLE [dbo].[Appointment] (
[Id] INT IDENTITY (1, 1) NOT NULL,
[FirstName] VARCHAR  NOT NULL,
[LastName] VARCHAR  NOT NULL,
[Type] VARCHAR (MAX) NOT NULL,
[Description] VARCHAR (MAX),
[DoctorID]  VARCHAR (MAX),
[Venue] VARCHAR (MAX) NOT NULL,
[StartTime] DATETIME NOT NULL,
[EndTime] DATETIME,
[User_Id] nvarchar(128) NOT NULL,
PRIMARY KEY CLUSTERED ([Id] ASC),
FOREIGN KEY (User_Id) REFERENCES AspNetUsers(Id)

);